# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'letter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1050, 100)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.form = Form
        self.horizontalLayoutWidget = QtWidgets.QWidget()
        self.form.setCentralWidget(self.horizontalLayoutWidget)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.vertical_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.question_field = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.vertical_layout.addWidget(self.question_field)

        QtCore.QMetaObject.connectSlotsByName(Form)

